//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altairis.ReP.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Altairis.ReP.Web.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string _Cancel {
            get {
                return ResourceManager.GetString("_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create....
        /// </summary>
        public static string _Create {
            get {
                return ResourceManager.GetString("_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string _Delete {
            get {
                return ResourceManager.GetString("_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string _No {
            get {
                return ResourceManager.GetString("_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string _OK {
            get {
                return ResourceManager.GetString("_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string _Submit {
            get {
                return ResourceManager.GetString("_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string _Yes {
            get {
                return ResourceManager.GetString("_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New directory entry was created successfully..
        /// </summary>
        public static string Admin_DirectoryEntries_Index_Msg_Created {
            get {
                return ResourceManager.GetString("Admin_DirectoryEntries_Index_Msg_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory entry was deleted..
        /// </summary>
        public static string Admin_DirectoryEntries_Index_Msg_Deleted {
            get {
                return ResourceManager.GetString("Admin_DirectoryEntries_Index_Msg_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory entry was saved..
        /// </summary>
        public static string Admin_DirectoryEntries_Index_Msg_Saved {
            get {
                return ResourceManager.GetString("Admin_DirectoryEntries_Index_Msg_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory entries.
        /// </summary>
        public static string Admin_DirectoryEntries_Title {
            get {
                return ResourceManager.GetString("Admin_DirectoryEntries_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit directory entry.
        /// </summary>
        public static string Admin_DirectoryEntry_Edit_Title {
            get {
                return ResourceManager.GetString("Admin_DirectoryEntry_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage directory entries.
        /// </summary>
        public static string Admin_Index_ManageDirectory {
            get {
                return ResourceManager.GetString("Admin_Index_ManageDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage news messages.
        /// </summary>
        public static string Admin_Index_ManageNews {
            get {
                return ResourceManager.GetString("Admin_Index_ManageNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage opening hours.
        /// </summary>
        public static string Admin_Index_ManageOpeningHours {
            get {
                return ResourceManager.GetString("Admin_Index_ManageOpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage reservations.
        /// </summary>
        public static string Admin_Index_ManageReservations {
            get {
                return ResourceManager.GetString("Admin_Index_ManageReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage resources.
        /// </summary>
        public static string Admin_Index_ManageResources {
            get {
                return ResourceManager.GetString("Admin_Index_ManageResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        public static string Admin_Index_ManageUsers {
            get {
                return ResourceManager.GetString("Admin_Index_ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System administration.
        /// </summary>
        public static string Admin_Index_Title {
            get {
                return ResourceManager.GetString("Admin_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new news message.
        /// </summary>
        public static string Admin_NewsMessages_Create_Title {
            get {
                return ResourceManager.GetString("Admin_NewsMessages_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this message?.
        /// </summary>
        public static string Admin_NewsMessages_Edit_DeleteConfirm {
            get {
                return ResourceManager.GetString("Admin_NewsMessages_Edit_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit news message.
        /// </summary>
        public static string Admin_NewsMessages_Edit_Title {
            get {
                return ResourceManager.GetString("Admin_NewsMessages_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New message was created successfully..
        /// </summary>
        public static string Admin_NewsMessages_Index_Msg_Created {
            get {
                return ResourceManager.GetString("Admin_NewsMessages_Index_Msg_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was successfully deleted..
        /// </summary>
        public static string Admin_NewsMessages_Index_Msg_Deleted {
            get {
                return ResourceManager.GetString("Admin_NewsMessages_Index_Msg_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was changed successfully..
        /// </summary>
        public static string Admin_NewsMessages_Index_Msg_Saved {
            get {
                return ResourceManager.GetString("Admin_NewsMessages_Index_Msg_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News messages.
        /// </summary>
        public static string Admin_NewsMessages_Index_Title {
            get {
                return ResourceManager.GetString("Admin_NewsMessages_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add exception.
        /// </summary>
        public static string Admin_OpeningHours_Add {
            get {
                return ResourceManager.GetString("Admin_OpeningHours_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If it&apos;s closed all day, set both opening and closing time to midnight..
        /// </summary>
        public static string Admin_OpeningHours_Add_Text {
            get {
                return ResourceManager.GetString("Admin_OpeningHours_Add_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this opening hours exception?.
        /// </summary>
        public static string Admin_OpeningHours_DeleteConfirm {
            get {
                return ResourceManager.GetString("Admin_OpeningHours_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions.
        /// </summary>
        public static string Admin_OpeningHours_Exceptions {
            get {
                return ResourceManager.GetString("Admin_OpeningHours_Exceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening hours exception was created successfully..
        /// </summary>
        public static string Admin_OpeningHours_Msg_Created {
            get {
                return ResourceManager.GetString("Admin_OpeningHours_Msg_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening hours exception was deleted successfully..
        /// </summary>
        public static string Admin_OpeningHours_Msg_Deleted {
            get {
                return ResourceManager.GetString("Admin_OpeningHours_Msg_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Admin_OpeningHours_Standard {
            get {
                return ResourceManager.GetString("Admin_OpeningHours_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening hours.
        /// </summary>
        public static string Admin_OpeningHours_Title {
            get {
                return ResourceManager.GetString("Admin_OpeningHours_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes of resource reservation were saved successfully..
        /// </summary>
        public static string Admin_Reservations_Edit_Msg_Saved {
            get {
                return ResourceManager.GetString("Admin_Reservations_Edit_Msg_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit reservation of {0} by {1}.
        /// </summary>
        public static string Admin_Reservations_Edit_Title {
            get {
                return ResourceManager.GetString("Admin_Reservations_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All reservations.
        /// </summary>
        public static string Admin_Reservations_Index_Title {
            get {
                return ResourceManager.GetString("Admin_Reservations_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no reservations in the system..
        /// </summary>
        public static string Admin_Reservations_NoReservations {
            get {
                return ResourceManager.GetString("Admin_Reservations_NoReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new attachment.
        /// </summary>
        public static string Admin_Resources_Attachments_AddAttachment {
            get {
                return ResourceManager.GetString("Admin_Resources_Attachments_AddAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this attachment?.
        /// </summary>
        public static string Admin_Resources_Attachments_ConfirmDelete {
            get {
                return ResourceManager.GetString("Admin_Resources_Attachments_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current attachments.
        /// </summary>
        public static string Admin_Resources_Attachments_Current {
            get {
                return ResourceManager.GetString("Admin_Resources_Attachments_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments for {0}.
        /// </summary>
        public static string Admin_Resources_Attachments_Title {
            get {
                return ResourceManager.GetString("Admin_Resources_Attachments_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new resource.
        /// </summary>
        public static string Admin_Resources_Create_Title {
            get {
                return ResourceManager.GetString("Admin_Resources_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this resource and all its related data? This action cannot be undone..
        /// </summary>
        public static string Admin_Resources_Edit_DeleteConfirm {
            get {
                return ResourceManager.GetString("Admin_Resources_Edit_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit resource.
        /// </summary>
        public static string Admin_Resources_Edit_Title {
            get {
                return ResourceManager.GetString("Admin_Resources_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New resource was created successfully..
        /// </summary>
        public static string Admin_Resources_Index_Msg_Created {
            get {
                return ResourceManager.GetString("Admin_Resources_Index_Msg_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource was successfully deleted..
        /// </summary>
        public static string Admin_Resources_Index_Msg_Deleted {
            get {
                return ResourceManager.GetString("Admin_Resources_Index_Msg_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource changes were saved successfully..
        /// </summary>
        public static string Admin_Resources_Index_Msg_Saved {
            get {
                return ResourceManager.GetString("Admin_Resources_Index_Msg_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Admin_Resources_Index_Title {
            get {
                return ResourceManager.GetString("Admin_Resources_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user was created successfully..
        /// </summary>
        public static string Admin_User_Index_Msg_Created {
            get {
                return ResourceManager.GetString("Admin_User_Index_Msg_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was successfully deleted..
        /// </summary>
        public static string Admin_User_Index_Msg_Deleted {
            get {
                return ResourceManager.GetString("Admin_User_Index_Msg_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User changes were saved successfully..
        /// </summary>
        public static string Admin_User_Index_Msg_Saved {
            get {
                return ResourceManager.GetString("Admin_User_Index_Msg_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System will send welcome message to newly created user&apos;s e-mail address. To activate account and set password, the user has to follow link contained in the message..
        /// </summary>
        public static string Admin_Users_Create_Text {
            get {
                return ResourceManager.GetString("Admin_Users_Create_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user.
        /// </summary>
        public static string Admin_Users_Create_Title {
            get {
                return ResourceManager.GetString("Admin_Users_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this user and all its related data? This action cannot be undone..
        /// </summary>
        public static string Admin_Users_Edit_DeleteConfirm {
            get {
                return ResourceManager.GetString("Admin_Users_Edit_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string Admin_Users_Edit_Title {
            get {
                return ResourceManager.GetString("Admin_Users_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is disabled.
        /// </summary>
        public static string Admin_Users_Index_Disabled {
            get {
                return ResourceManager.GetString("Admin_Users_Index_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is enabled.
        /// </summary>
        public static string Admin_Users_Index_Enabled {
            get {
                return ResourceManager.GetString("Admin_Users_Index_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Admin_Users_Index_Title {
            get {
                return ResourceManager.GetString("Admin_Users_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is waiting to be activated.
        /// </summary>
        public static string Admin_Users_Index_Waiting {
            get {
                return ResourceManager.GetString("Admin_Users_Index_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - My calendar.
        /// </summary>
        public static string Cal_My_Name {
            get {
                return ResourceManager.GetString("Cal_My_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string Cal_Resource_Name {
            get {
                return ResourceManager.GetString("Cal_Resource_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d..
        /// </summary>
        public static string Calendar_GeneralDateFormat {
            get {
                return ResourceManager.GetString("Calendar_GeneralDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMMM d..
        /// </summary>
        public static string Calendar_NewMonthDateFormat {
            get {
                return ResourceManager.GetString("Calendar_NewMonthDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no users defined in application. Please create first user who will become an administrator..
        /// </summary>
        public static string FirstRun_Text {
            get {
                return ResourceManager.GetString("FirstRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create admin user.
        /// </summary>
        public static string FirstRun_Title {
            get {
                return ResourceManager.GetString("FirstRun_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Layout_LoginStatus_SignIn {
            get {
                return ResourceManager.GetString("Layout_LoginStatus_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Layout_LoginStatus_SignOut {
            get {
                return ResourceManager.GetString("Layout_LoginStatus_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Layout_Menu_Administration {
            get {
                return ResourceManager.GetString("Layout_Menu_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Layout_Menu_Calendar {
            get {
                return ResourceManager.GetString("Layout_Menu_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string Layout_Menu_Directory {
            get {
                return ResourceManager.GetString("Layout_Menu_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Layout_Menu_Home {
            get {
                return ResourceManager.GetString("Layout_Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string Layout_Menu_Journal {
            get {
                return ResourceManager.GetString("Layout_Menu_Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Layout_Menu_Login {
            get {
                return ResourceManager.GetString("Layout_Menu_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string Layout_Menu_News {
            get {
                return ResourceManager.GetString("Layout_Menu_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string Layout_Menu_ResetPassword {
            get {
                return ResourceManager.GetString("Layout_Menu_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Layout_Menu_Settings {
            get {
                return ResourceManager.GetString("Layout_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Welcome to the ReP IS! Your user name is &lt;b&gt;{0}&lt;/b&gt;.&lt;/p&gt;
        ///&lt;p&gt;Please create a password to activate your account. The password should be long and unique. Consider using a &lt;i&gt;passphrase&lt;/i&gt;, entire sentence. It&apos;s easier to remember and more secure than typical password.&lt;/p&gt;.
        /// </summary>
        public static string Login_Activate_Html {
            get {
                return ResourceManager.GetString("Login_Activate_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate your new account.
        /// </summary>
        public static string Login_Activate_Title {
            get {
                return ResourceManager.GetString("Login_Activate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this user does exist, we will send password reset instructions to it&apos;s e-mail address..
        /// </summary>
        public static string Login_ForgotPassword_Text {
            get {
                return ResourceManager.GetString("Login_ForgotPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset forgotten password.
        /// </summary>
        public static string Login_ForgotPassword_Title {
            get {
                return ResourceManager.GetString("Login_ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified user was not found..
        /// </summary>
        public static string Login_ForgotPassword_UserNotFound {
            get {
                return ResourceManager.GetString("Login_ForgotPassword_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed..
        /// </summary>
        public static string Login_Index_LoginFailed {
            get {
                return ResourceManager.GetString("Login_Index_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was successfully activated.
        ///You may now login with your new password..
        /// </summary>
        public static string Login_Index_Msg_ADone {
            get {
                return ResourceManager.GetString("Login_Index_Msg_ADone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User activation failed. 
        ///Please check that the link you visited is correct and complete. 
        ///The user may also have been activated before..
        /// </summary>
        public static string Login_Index_Msg_AFail {
            get {
                return ResourceManager.GetString("Login_Index_Msg_AFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were successfully signed out..
        /// </summary>
        public static string Login_Index_Msg_Logout {
            get {
                return ResourceManager.GetString("Login_Index_Msg_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was reset successfully.
        ///You may now login with your new password..
        /// </summary>
        public static string Login_Index_Msg_Reset {
            get {
                return ResourceManager.GetString("Login_Index_Msg_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset instructions were sent to e-mail address registered for this account.
        ///Please follow the instructions in the message..
        /// </summary>
        public static string Login_Index_Msg_Sent {
            get {
                return ResourceManager.GetString("Login_Index_Msg_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Index_Title {
            get {
                return ResourceManager.GetString("Login_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup new password.
        /// </summary>
        public static string Login_ResetPassword_Title {
            get {
                return ResourceManager.GetString("Login_ResetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no reservations..
        /// </summary>
        public static string My_Archive_NoReservations {
            get {
                return ResourceManager.GetString("My_Archive_NoReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add entry.
        /// </summary>
        public static string My_Calendar_AddEntry {
            get {
                return ResourceManager.GetString("My_Calendar_AddEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to my calendar.
        /// </summary>
        public static string My_Calendar_Ics {
            get {
                return ResourceManager.GetString("My_Calendar_Ics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage my reservations.
        /// </summary>
        public static string My_Calendar_Manage {
            get {
                return ResourceManager.GetString("My_Calendar_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation calendar for {0:y}.
        /// </summary>
        public static string My_Calendar_Title {
            get {
                return ResourceManager.GetString("My_Calendar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is empty..
        /// </summary>
        public static string My_Directory_IsEmpty {
            get {
                return ResourceManager.GetString("My_Directory_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string My_Directory_Title {
            get {
                return ResourceManager.GetString("My_Directory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All my reservations.
        /// </summary>
        public static string My_Index_Archive {
            get {
                return ResourceManager.GetString("My_Index_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reservation was successfully deleted..
        /// </summary>
        public static string My_Index_Msg_ReservationDeleted {
            get {
                return ResourceManager.GetString("My_Index_Msg_ReservationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current reservations..
        /// </summary>
        public static string My_Index_NoReservations {
            get {
                return ResourceManager.GetString("My_Index_NoReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More opening hours....
        /// </summary>
        public static string My_Index_OpeningHours {
            get {
                return ResourceManager.GetString("My_Index_OpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My upcoming reservations.
        /// </summary>
        public static string My_Index_Reservations {
            get {
                return ResourceManager.GetString("My_Index_Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available resources.
        /// </summary>
        public static string My_Index_Resources {
            get {
                return ResourceManager.GetString("My_Index_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ReP - the resource reservation system!.
        /// </summary>
        public static string My_Index_Title {
            get {
                return ResourceManager.GetString("My_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today is &lt;b&gt;closed&lt;/b&gt;..
        /// </summary>
        public static string My_Index_TodayLab_Closed {
            get {
                return ResourceManager.GetString("My_Index_TodayLab_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today is &lt;b&gt;open {0}&lt;/b&gt;..
        /// </summary>
        public static string My_Index_TodayLab_Open {
            get {
                return ResourceManager.GetString("My_Index_TodayLab_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow is closed..
        /// </summary>
        public static string My_Index_TomorrowLab_Closed {
            get {
                return ResourceManager.GetString("My_Index_TomorrowLab_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow is open {0}..
        /// </summary>
        public static string My_Index_TomorrowLab_Open {
            get {
                return ResourceManager.GetString("My_Index_TomorrowLab_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New journal entry was created successfully..
        /// </summary>
        public static string My_Journal_Msg_Created {
            get {
                return ResourceManager.GetString("My_Journal_Msg_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New journal entry.
        /// </summary>
        public static string My_Journal_New {
            get {
                return ResourceManager.GetString("My_Journal_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no journal entries yet..
        /// </summary>
        public static string My_Journal_NoEntries {
            get {
                return ResourceManager.GetString("My_Journal_NoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n/a.
        /// </summary>
        public static string My_Journal_ResourceUnspecified {
            get {
                return ResourceManager.GetString("My_Journal_ResourceUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string My_Journal_Title {
            get {
                return ResourceManager.GetString("My_Journal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no news published..
        /// </summary>
        public static string My_News_NoNews {
            get {
                return ResourceManager.GetString("My_News_NoNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string My_News_Title {
            get {
                return ResourceManager.GetString("My_News_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to closed.
        /// </summary>
        public static string My_OpeningHours_Closed {
            get {
                return ResourceManager.GetString("My_OpeningHours_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening hours.
        /// </summary>
        public static string My_OpeningHours_Title {
            get {
                return ResourceManager.GetString("My_OpeningHours_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string My_Reservations_Attachments {
            get {
                return ResourceManager.GetString("My_Reservations_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this reservation?.
        /// </summary>
        public static string My_Reservations_DeleteConfirm {
            get {
                return ResourceManager.GetString("My_Reservations_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This reservation conflicts with {0}&apos;s reservation from {1:d} {1:t}..
        /// </summary>
        public static string My_Reservations_Err_Conflict {
            get {
                return ResourceManager.GetString("My_Reservations_Err_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum reservation time for this resource is {0} minutes..
        /// </summary>
        public static string My_Reservations_Err_Maxlength {
            get {
                return ResourceManager.GetString("My_Reservations_Err_Maxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation is outside of opening hours..
        /// </summary>
        public static string My_Reservations_Err_OpeningHours {
            get {
                return ResourceManager.GetString("My_Reservations_Err_OpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation cannot span multiple days..
        /// </summary>
        public static string My_Reservations_Err_SingleDay {
            get {
                return ResourceManager.GetString("My_Reservations_Err_SingleDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reservation was created successfully..
        /// </summary>
        public static string My_Reservations_Msg_Created {
            get {
                return ResourceManager.GetString("My_Reservations_Msg_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New reservation.
        /// </summary>
        public static string My_Reservations_New {
            get {
                return ResourceManager.GetString("My_Reservations_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new reservation.
        /// </summary>
        public static string My_Reservations_NewTitle {
            get {
                return ResourceManager.GetString("My_Reservations_NewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to reset the calendar access token? You would need to change the calendar address everywhere you are using it..
        /// </summary>
        public static string My_Setting_ResetRak_Confirm {
            get {
                return ResourceManager.GetString("My_Setting_ResetRak_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        public static string My_Settings_Email_InvalidPassword {
            get {
                return ResourceManager.GetString("My_Settings_Email_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change my e-mail address.
        /// </summary>
        public static string My_Settings_Email_Title {
            get {
                return ResourceManager.GetString("My_Settings_Email_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Confirmation failed. The usual reasons are:&lt;/p&gt; 
        ///&lt;ul&gt;
        ///&lt;li&gt;The page address is incorrect or incomplete. It may have been wrapped into multiple lines by your e-mail client.&lt;/li&gt;
        ///&lt;li&gt;The desired e-mail address is already used by another account on this system.&lt;/li&gt;
        ///&lt;li&gt;The change was already confirmed.&lt;/li&gt;
        ///&lt;li&gt;The confirmation link is outdated. Please initiate the change again.&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string My_Settings_EmailConfirm_FailedHtml {
            get {
                return ResourceManager.GetString("My_Settings_EmailConfirm_FailedHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string My_Settings_EmailConfirm_TryAgain {
            get {
                return ResourceManager.GetString("My_Settings_EmailConfirm_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All reservations.
        /// </summary>
        public static string My_Settings_Ics_Full {
            get {
                return ResourceManager.GetString("My_Settings_Ics_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My reservations only.
        /// </summary>
        public static string My_Settings_Ics_My {
            get {
                return ResourceManager.GetString("My_Settings_Ics_My", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset calendar access token.
        /// </summary>
        public static string My_Settings_Ics_ResetRak {
            get {
                return ResourceManager.GetString("My_Settings_Ics_ResetRak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change....
        /// </summary>
        public static string My_Settings_Index_Change {
            get {
                return ResourceManager.GetString("My_Settings_Index_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We just sent an e-mail to a new address you entered. Please follow the link in the message to confirm the e-mail change..
        /// </summary>
        public static string My_Settings_Index_Msg_ChangeEmail {
            get {
                return ResourceManager.GetString("My_Settings_Index_Msg_ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-mail address was changed successfully..
        /// </summary>
        public static string My_Settings_Index_Msg_ChangeEmailDone {
            get {
                return ResourceManager.GetString("My_Settings_Index_Msg_ChangeEmailDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was changed successfully..
        /// </summary>
        public static string My_Settings_Index_Msg_ChangePassword {
            get {
                return ResourceManager.GetString("My_Settings_Index_Msg_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change your username, please contact system administrator..
        /// </summary>
        public static string My_Settings_Index_Msg_ChangeUserName {
            get {
                return ResourceManager.GetString("My_Settings_Index_Msg_ChangeUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To delete your account, please contact system administrator..
        /// </summary>
        public static string My_Settings_Index_Msg_Delete {
            get {
                return ResourceManager.GetString("My_Settings_Index_Msg_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your calendar access token was changed and old calendar URLs are no longer valid..
        /// </summary>
        public static string My_Settings_Index_Msg_ResetRakDone {
            get {
                return ResourceManager.GetString("My_Settings_Index_Msg_ResetRakDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes were saved successfully..
        /// </summary>
        public static string My_Settings_Index_Msg_Saved {
            get {
                return ResourceManager.GetString("My_Settings_Index_Msg_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My settings.
        /// </summary>
        public static string My_Settings_Index_Title {
            get {
                return ResourceManager.GetString("My_Settings_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account-related messages (always allowed).
        /// </summary>
        public static string My_Settings_Mailing_System {
            get {
                return ResourceManager.GetString("My_Settings_Mailing_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change my password.
        /// </summary>
        public static string My_Settings_Password_Title {
            get {
                return ResourceManager.GetString("My_Settings_Password_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string My_Settings_Privacy {
            get {
                return ResourceManager.GetString("My_Settings_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today, {0:t}.
        /// </summary>
        public static string TimeTagHelper_Today {
            get {
                return ResourceManager.GetString("TimeTagHelper_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow, {0:t}.
        /// </summary>
        public static string TimeTagHelper_Tomorrow {
            get {
                return ResourceManager.GetString("TimeTagHelper_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday, {0:t}.
        /// </summary>
        public static string TimeTagHelper_Yesterday {
            get {
                return ResourceManager.GetString("TimeTagHelper_Yesterday", resourceCulture);
            }
        }
    }
}
