//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altairis.FutLabIS.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mailing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mailing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Altairis.FutLabIS.Web.Resources.Mailing", typeof(Mailing).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate your new account.
        /// </summary>
        public static string Activation_Subject {
            get {
                return ResourceManager.GetString("Activation_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///this e-mail is to inform you that a new account {{userName}} was created for you in the FutLab IS.
        ///
        ///To activate this account and set your password, please visit the following page:
        ///{{url}}
        ///.
        /// </summary>
        public static string Activation_Text {
            get {
                return ResourceManager.GetString("Activation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///--
        ///You are receiving this message as member of FutLab.
        ///You may configure the mailing options in the FutLab IS: https://is.futlab.cc/
        ///.
        /// </summary>
        public static string BodyTextFormatString {
            get {
                return ResourceManager.GetString("BodyTextFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm change of your e-mail address.
        /// </summary>
        public static string EmailConfirm_Subject {
            get {
                return ResourceManager.GetString("EmailConfirm_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///someone (most likely you) requested e-mail address for the FutLab account {{userName}} to be changed to this one.
        ///
        ///If you do not want to change the e-mail, you can safely ignore this message.
        ///
        ///If you do want to confirm the change, go to the following page:
        ///{{url}}
        ///.
        /// </summary>
        public static string EmailConfirm_Text {
            get {
                return ResourceManager.GetString("EmailConfirm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{title}}.
        /// </summary>
        public static string News_Subject {
            get {
                return ResourceManager.GetString("News_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///the following news was published in the FutLab IS:
        ///
        ///{{text}}.
        /// </summary>
        public static string News_Text {
            get {
                return ResourceManager.GetString("News_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string PasswordReset_Subject {
            get {
                return ResourceManager.GetString("PasswordReset_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///someone (most likely you) requested password reset for the FutLab account {{userName}}.
        ///
        ///If you do not want to reset the password, you can safely ignore this message.
        ///
        ///If you do want to reset the password, go to the following page:
        ///{{url}}
        ///.
        /// </summary>
        public static string PasswordReset_Text {
            get {
                return ResourceManager.GetString("PasswordReset_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reservation was changed.
        /// </summary>
        public static string ReservationChanged_Subject {
            get {
                return ResourceManager.GetString("ReservationChanged_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///this message is to inform you that your reservation of {{resourceName}} was changed by {{userName}}.
        ///
        ///Original reservation was from {{oldDateBegin}} to {{oldDateEnd}}.
        ///
        ///Current reservation is from {{dateBegin}} to {{dateEnd}}.
        ///
        ///.
        /// </summary>
        public static string ReservationChanged_Text {
            get {
                return ResourceManager.GetString("ReservationChanged_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reservation was deleted.
        /// </summary>
        public static string ReservationDeleted_Subject {
            get {
                return ResourceManager.GetString("ReservationDeleted_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///this message is to inform you that your reservation of {{resourceName}} was deleted by {{userName}}.
        ///
        ///Original reservation was from {{oldDateBegin}} to {{oldDateEnd}}.
        ///
        ///.
        /// </summary>
        public static string ReservationDeleted_Text {
            get {
                return ResourceManager.GetString("ReservationDeleted_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [FutLab IS] {0}.
        /// </summary>
        public static string SubjectFormatString {
            get {
                return ResourceManager.GetString("SubjectFormatString", resourceCulture);
            }
        }
    }
}
