//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altairis.FutLabIS.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Altairis.FutLabIS.Web.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string _Cancel {
            get {
                return ResourceManager.GetString("_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string _No {
            get {
                return ResourceManager.GetString("_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string _OK {
            get {
                return ResourceManager.GetString("_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string _Submit {
            get {
                return ResourceManager.GetString("_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string _Yes {
            get {
                return ResourceManager.GetString("_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user was created successfully..
        /// </summary>
        public static string Admin_User_Index_Msg_Created {
            get {
                return ResourceManager.GetString("Admin_User_Index_Msg_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System will send welcome message to newly created user&apos;s e-mail address. To activate account and set password, the user has to follow link contained in the message..
        /// </summary>
        public static string Admin_Users_Create_Text {
            get {
                return ResourceManager.GetString("Admin_Users_Create_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user.
        /// </summary>
        public static string Admin_Users_Create_Title {
            get {
                return ResourceManager.GetString("Admin_Users_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is disabled.
        /// </summary>
        public static string Admin_Users_Index_Disabled {
            get {
                return ResourceManager.GetString("Admin_Users_Index_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is enabled.
        /// </summary>
        public static string Admin_Users_Index_Enabled {
            get {
                return ResourceManager.GetString("Admin_Users_Index_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user....
        /// </summary>
        public static string Admin_Users_Index_New {
            get {
                return ResourceManager.GetString("Admin_Users_Index_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Admin_Users_Index_Title {
            get {
                return ResourceManager.GetString("Admin_Users_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is waiting to be activated.
        /// </summary>
        public static string Admin_Users_Index_Waiting {
            get {
                return ResourceManager.GetString("Admin_Users_Index_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no users defined in application. Please create first user who will become an administrator..
        /// </summary>
        public static string FirstRun_Text {
            get {
                return ResourceManager.GetString("FirstRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create admin user.
        /// </summary>
        public static string FirstRun_Title {
            get {
                return ResourceManager.GetString("FirstRun_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Layout_LoginStatus_SignIn {
            get {
                return ResourceManager.GetString("Layout_LoginStatus_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Layout_LoginStatus_SignOut {
            get {
                return ResourceManager.GetString("Layout_LoginStatus_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Welcome to the FutLab IS! Your user name is &lt;b&gt;{0}&lt;/b&gt;.&lt;/p&gt;
        ///&lt;p&gt;Please create a password to activate your account. The password should be long and unique. Consider using a &lt;i&gt;passphrase&lt;/i&gt;, entire sentence. It&apos;s easier to remember and more secure than typical password.&lt;/p&gt;.
        /// </summary>
        public static string Login_Activate_Html {
            get {
                return ResourceManager.GetString("Login_Activate_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate your new account.
        /// </summary>
        public static string Login_Activate_Title {
            get {
                return ResourceManager.GetString("Login_Activate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this user does exist, we will send password reset instructions to it&apos;s e-mail address..
        /// </summary>
        public static string Login_ForgotPassword_Text {
            get {
                return ResourceManager.GetString("Login_ForgotPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset forgotten password.
        /// </summary>
        public static string Login_ForgotPassword_Title {
            get {
                return ResourceManager.GetString("Login_ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified user was not found..
        /// </summary>
        public static string Login_ForgotPassword_UserNotFound {
            get {
                return ResourceManager.GetString("Login_ForgotPassword_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed..
        /// </summary>
        public static string Login_Index_LoginFailed {
            get {
                return ResourceManager.GetString("Login_Index_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was successfully activated.
        ///You may now login with your new password..
        /// </summary>
        public static string Login_Index_Msg_ADone {
            get {
                return ResourceManager.GetString("Login_Index_Msg_ADone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User activation failed. 
        ///Please check that the link you visited is correct and complete. 
        ///The user may also have been activated before..
        /// </summary>
        public static string Login_Index_Msg_AFail {
            get {
                return ResourceManager.GetString("Login_Index_Msg_AFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were successfully signed out..
        /// </summary>
        public static string Login_Index_Msg_Logout {
            get {
                return ResourceManager.GetString("Login_Index_Msg_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was reset successfully.
        ///You may now login with your new password..
        /// </summary>
        public static string Login_Index_Msg_Reset {
            get {
                return ResourceManager.GetString("Login_Index_Msg_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset instructions were sent to e-mail address registered for this account.
        ///Please follow the instructions in the message..
        /// </summary>
        public static string Login_Index_Msg_Sent {
            get {
                return ResourceManager.GetString("Login_Index_Msg_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Index_Title {
            get {
                return ResourceManager.GetString("Login_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup new password.
        /// </summary>
        public static string Login_ResetPassword_Title {
            get {
                return ResourceManager.GetString("Login_ResetPassword_Title", resourceCulture);
            }
        }
    }
}
